onlyBuiltDependencies:
  - "@apollo/protobufjs"
  - "@swc/core"
  - core-js-pure
  - esbuild
  - sharp

minimumReleaseAgeExclude:
  - pg-connection-string@2.14.0
  - pg-protocol@1.15.0
  - pg@8.22.0

allowBuilds:
  '@apollo/protobufjs': true
  '@swc/core': true
  core-js-pure: true
  esbuild: true
  sharp: true
