#!/usr/bin/env bash
# Generates the .env consumed by docker-compose.yml with random secrets.
# Usage: ./scripts/generate-env.sh [--force]
set -euo pipefail

cd "$(dirname "$0")/.."

if [[ -f .env && "${1:-}" != "--force" ]]; then
  echo "ERROR: .env already exists — pass --force to overwrite it." >&2
  exit 1
fi

rand() { openssl rand -base64 "$1" | tr -d '\n'; }

cat > .env <<EOF
# Generated by scripts/generate-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

# --- Build mode: development (test servers, merges override) | production ---
BUILD_ENV=development

# --- MySQL ---
DB_ROOT_PASSWORD=$(rand 24)
DB_NAME=foues
DB_USER=foues
DB_PASSWORD=$(rand 24)

# --- Strapi secrets ---
STRAPI_APP_KEYS=$(rand 16),$(rand 16),$(rand 16),$(rand 16)
STRAPI_API_TOKEN_SALT=$(rand 16)
STRAPI_ADMIN_JWT_SECRET=$(rand 16)
STRAPI_TRANSFER_TOKEN_SALT=$(rand 16)
STRAPI_ENCRYPTION_KEY=$(rand 32)
STRAPI_JWT_SECRET=$(rand 16)

# --- Frontend ---
# URL the frontend uses to reach the API — adjust to your environment.
STRAPI_URL=http://foues-cms-api:1337
# Fill these once the API is up, by running:
#   docker compose run --rm foues-cms-api node scripts/create-api-tokens.js
STRAPI_API_TOKEN=
FORM_SUBMIT_TOKEN=
MAGAZINE_TRACK_TOKEN=

# --- NextAuth ---
# Set AUTH_URL / NEXTAUTH_URL to the public URL of the frontend (e.g. http://<server-ip>:3000).
AUTH_SECRET=$(rand 32)
AUTH_URL=http://localhost:3000
NEXTAUTH_URL=http://localhost:3000
GOOGLE_CLIENT_ID=dummy
GOOGLE_CLIENT_SECRET=dummy

# --- Cache revalidation ---
REVALIDATE_SECRET=$(rand 32)
EOF

echo ".env generated."
echo "Next: start the stack, then create the API tokens:"
echo "  docker compose -f docker-compose.yml run --rm foues-cms-api node scripts/create-api-tokens.js"
